baseURL = "https://the-rdk.github.io/rdk_website/"
languageCode = "en-us"
title = "The RDK"
theme = "hyde"
publishDir = "docs"

[params]
  description = "Research. Development. Kayaking."
  themeColor = "theme-base-0b"
