baseURL = "https://the-rdk.github.io/"
languageCode = "en-us"
title = "The RDK"
theme = "hyde"
publishDir = "docs"

[params]
  description = "Research. Development. Kayaking."
  themeColor = "theme-base-0b"

[Menus]
  main = [
    {Name = "Books", URL="/book"}
  ]