baseURL = "https://the-rdk.github.io/"
languageCode = "en-us"
title = "The RDK"
# https://github.com/Mitrichius/hugo-theme-anubis
theme = "anubis"
publishDir = "docs"

# https://codingnconcepts.com/hugo/multiple-authors-hugo/
[taxonomies]
  author = "authors"

[params]
  style = "dark"
  rssAsSocialIcon = true
  disableSummary = true
  readMore = false

[Menus]
  main = [
    {Name = "Articles", URL = "/article", weight = 2},
    {Name = "Home", URL = "/", weight = 1},
    {Name = "Book Club", URL = "/book", weight = 3},
  ]