baseURL = "https://the-rdk.github.io/"
languageCode = "en-us"
title = "The RDK"
# https://github.com/Mitrichius/hugo-theme-anubis
theme = "anubis"
publishDir = "docs"

[params]
  style = "dark"

[Menus]
  main = [
    {Name = "Articles", URL = "/article", weight = 2},
    {Name = "Home", URL = "/", weight = 1},
    {Name = "Book Club", URL = "/book", weight = 3},
  ]